$primary_paletteKeyColor = f9e501
$secondary_paletteKeyColor = 82792a
$tertiary_paletteKeyColor = c6f959
$neutral_paletteKeyColor = 7b7767
$neutral_variant_paletteKeyColor = 7c785f
$background = 151408
$onBackground = e8e2cf
$surface = 151408
$surfaceDim = 151408
$surfaceBright = 3c392c
$surfaceContainerLowest = 100e05
$surfaceContainerLow = 1e1c10
$surfaceContainer = 222014
$surfaceContainerHigh = 2c2a1d
$surfaceContainerHighest = 373528
$onSurface = e8e2cf
$surfaceVariant = 4a4732
$onSurfaceVariant = cdc7ab
$inverseSurface = e8e2cf
$inverseOnSurface = 333123
$outline = 969177
$outlineVariant = 4a4732
$shadow = 000000
$scrim = 000000
$surfaceTint = dac900
$primary = bcad00
$onPrimary = 252100
$primaryContainer = ffeb13
$onPrimaryContainer = 736900
$inversePrimary = 686000
$secondary = d4c971
$onSecondary = 363100
$secondaryContainer = 4f4800
$onSecondaryContainer = c2b761
$tertiary = a6d639
$onTertiary = 253600
$tertiaryContainer = 749e00
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = f9e502
$primaryFixedDim = dac900
$onPrimaryFixed = 1f1c00
$onPrimaryFixedVariant = 4f4800
$secondaryFixed = f1e58a
$secondaryFixedDim = d4c971
$onSecondaryFixed = 1f1c00
$onSecondaryFixedVariant = 4f4800
$tertiaryFixed = c1f354
$tertiaryFixedDim = a6d639
$onTertiaryFixed = 141f00
$onTertiaryFixedVariant = 374e00
$term0 = 353433
$term1 = b48b00
$term2 = dbcf4d
$term3 = ffe66f
$term4 = a2b174
$term5 = d3a343
$term6 = cbce78
$term7 = e0d8bf
$term8 = a9a290
$term9 = d1a200
$term10 = eee145
$term11 = fff4cb
$term12 = c0c49a
$term13 = e2b967
$term14 = e0e07e
$term15 = ffffff
$rosewater = faf0e0
$flamingo = f1e0c0
$pink = ffd79d
$mauve = ffad7f
$red = dfac3b
$maroon = deba70
$peach = e5cc7f
$yellow = fdf2bd
$green = e3e682
$teal = d9e799
$sky = cde495
$sapphire = b2d27f
$blue = 75cf9d
$lavender = 89dcc6
$klink = 559652
$klinkSelection = 559652
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = ab8200
$knegativeSelection = ab8200
$kneutral = cda700
$kneutralSelection = cda600
$kpositive = a8b10e
$kpositiveSelection = a8b10e
$text = e8e2cf
$subtext1 = cdc7ab
$subtext0 = 969177
$overlay2 = 837e66
$overlay1 = 6f6b55
$overlay0 = 5d5a46
$surface2 = 4b4937
$surface1 = 3a3828
$surface0 = 272618
$base = 151408
$mantle = 151408
$crust = 141308
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
